"""Contracts for read-only public benchmark workspaces.

The manifest is an allowlist, not a description generated by the model.  A
catalog must validate it before exposing any file to an Agent harness.
"""

from __future__ import annotations

from typing import Literal

from pydantic import Field, field_validator

from .models import StrictModel


BenchmarkContentNature = Literal["public_benchmark_input"]
BenchmarkFileRole = Literal["input", "task_instruction"]
BenchmarkTaskTopology = Literal["single_task", "multi_task"]
BenchmarkOrchestrationMode = Literal["bounded_loop", "adaptive_swarm"]
BenchmarkControlRequirement = Literal[
    "evidence_gate",
    "human_gate",
    "risk_gate",
]


class BenchmarkFileEntry(StrictModel):
    """One immutable, allowlisted file in a benchmark task."""

    path: str = Field(min_length=1, max_length=500)
    sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    size: int = Field(gt=0, le=10 * 1024 * 1024)
    mime: str = Field(min_length=1, max_length=160)
    role: BenchmarkFileRole

    @field_validator("path")
    @classmethod
    def validate_relative_path(cls, value: str) -> str:
        normalized = value.replace("\\", "/")
        if normalized != value or normalized.startswith("/"):
            raise ValueError("benchmark file path must use a relative POSIX path")
        if "\x00" in value or ":" in value or ".." in normalized.split("/"):
            raise ValueError("benchmark file path is unsafe")
        if any(not part for part in normalized.split("/")):
            raise ValueError("benchmark file path contains an empty segment")
        return value


class BenchmarkTaskEntry(StrictModel):
    """Task-level grouping used to expose a real input folder to a harness."""

    task_id: str = Field(min_length=1, max_length=120)
    category: str = Field(min_length=1, max_length=120)
    input_dir: str = Field(min_length=1, max_length=300)
    files: list[BenchmarkFileEntry] = Field(min_length=1, max_length=100)

    @field_validator("input_dir")
    @classmethod
    def validate_input_dir(cls, value: str) -> str:
        normalized = value.replace("\\", "/")
        if normalized != value or normalized.startswith("/"):
            raise ValueError("benchmark input_dir must use a relative POSIX path")
        if "\x00" in value or ":" in value or ".." in normalized.split("/"):
            raise ValueError("benchmark input_dir is unsafe")
        if any(not part for part in normalized.split("/")):
            raise ValueError("benchmark input_dir contains an empty segment")
        return value


class BenchmarkManifest(StrictModel):
    """Provenance and file allowlist for a public benchmark import."""

    schema_version: Literal["1.0"]
    dataset: str = Field(min_length=1, max_length=200)
    source_url: str = Field(min_length=1, max_length=1_000)
    source_commit: str = Field(pattern=r"^[0-9a-f]{40}$")
    license: str = Field(min_length=1, max_length=120)
    content_nature: BenchmarkContentNature
    tasks: list[BenchmarkTaskEntry] = Field(min_length=1, max_length=100)


class BenchmarkDisplayFile(StrictModel):
    """Business-facing file projection; raw path/hash stay server-side."""

    file_ref: str = Field(pattern=r"^forte-[0-9a-f]{16}$")
    display_label: str = Field(min_length=1, max_length=200)
    display_group: str = Field(min_length=1, max_length=120)
    display_summary: str = Field(min_length=1, max_length=500)


class BenchmarkPreviewRow(StrictModel):
    """One bounded row in a public spreadsheet preview."""

    row_number: int = Field(ge=1)
    values: list[str] = Field(max_length=30)


class BenchmarkFilePreview(StrictModel):
    """Allowlisted file content safe for the foreground data explorer."""

    scenario_id: str = Field(min_length=1, max_length=120)
    file_ref: str = Field(pattern=r"^forte-[0-9a-f]{16}$")
    display_label: str = Field(min_length=1, max_length=200)
    display_group: str = Field(min_length=1, max_length=120)
    display_summary: str = Field(min_length=1, max_length=500)
    kind: Literal["table", "markdown"]
    sheet_name: str | None = Field(default=None, max_length=120)
    columns: list[str] = Field(default_factory=list, max_length=30)
    rows: list[BenchmarkPreviewRow] = Field(default_factory=list, max_length=120)
    total_rows: int | None = Field(default=None, ge=0)
    text: str | None = Field(default=None, max_length=30_000)
    truncated: bool = False


class BenchmarkWorkProfile(StrictModel):
    """Scenario-neutral capability composition requested for a business task.

    The profile describes how the general Agent should organize work. It is not
    a claim that the current read-only Harness already executes that topology.
    """

    task_topology: BenchmarkTaskTopology
    orchestration: BenchmarkOrchestrationMode
    control_requirements: list[BenchmarkControlRequirement] = Field(
        min_length=1,
        max_length=3,
    )
    current_runtime_scope: Literal["read_only_analysis"] = "read_only_analysis"

    @field_validator("control_requirements")
    @classmethod
    def validate_unique_controls(
        cls,
        value: list[BenchmarkControlRequirement],
    ) -> list[BenchmarkControlRequirement]:
        if len(value) != len(set(value)):
            raise ValueError("work profile control requirements must be unique")
        return value


class BenchmarkPublicScenario(StrictModel):
    """Safe scenario contract returned to the foreground UI."""

    scenario_id: str = Field(min_length=1, max_length=120)
    work_profile: BenchmarkWorkProfile
    title: str = Field(min_length=1, max_length=200)
    goal: str = Field(min_length=1, max_length=1_000)
    deliverables: list[str] = Field(min_length=1, max_length=12)
    data_boundary: str = Field(min_length=1, max_length=500)
    human_gate_summary: str = Field(min_length=1, max_length=500)
    allowed_capabilities: list[str] = Field(min_length=1, max_length=16)
    dataset_label: str = Field(min_length=1, max_length=200)
    dataset_version: str = Field(min_length=1, max_length=120)
    files: list[BenchmarkDisplayFile] = Field(min_length=1, max_length=100)
